spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ordersdb?currentSchema=op
    username: tu-usuario
    password: tus-credenciales
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: op
        show_sql: true